{% set name = "plyvel" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3caf6009e4fc24fbf8712d3f5ef3da7e56495c26a488df2161218fc34e46019c

build:
  number: 2
  script:
    - cythonize plyvel/_plyvel.pyx
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - cython
    - python
    - leveldb
    - setuptools
  run:
    - python
    - leveldb

test:
  imports:
    - plyvel

about:
  home: https://pypi.org/project/plyvel/
  summary: Plyvel, a fast and feature-rich Python interface to LevelDB
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
